import { inject, injectable } from 'tsyringe';
import { IUserRepository } from '../../domain/repositories/IUserRepository';
import { IPasswordService } from '../../domain/services/IPasswordService';
import { IJwtService } from '../../domain/services/IJwtService';
import { User } from '../../domain/entities/User';
import { UserRole } from '../../constants/enums/UserRole';
import { IEmailService } from '../../domain/services/IEmailService';
import { UserOTPVerificationModel } from '../../infrastructure/database/models/UserOTPVerificationModel';
import { UserModel } from '../../infrastructure/database/models/UserModel';
import { WalletModel } from '../../infrastructure/database/models/WalletModel';
import { IRegisterUseCase, RegisterRequest, RegisterResponse } from '../interfaces/IRegisterUseCase';
import crypto from 'crypto';

@injectable()
export class RegisterUseCase implements IRegisterUseCase {
    constructor(
        @inject('IUserRepository') private userRepository: IUserRepository,
        @inject('IPasswordService') private passwordService: IPasswordService,
        @inject('IJwtService') private jwtService: IJwtService,
        @inject('IEmailService') private emailService: IEmailService
    ) { }

    async execute(data: RegisterRequest): Promise<RegisterResponse> {
        // 1. Validate if Email is already in use
        const existingEmailUser = await this.userRepository.findByEmail(data.email);
        if (existingEmailUser) {
            throw new Error('Email address is already registered');
        }

        // 2. Validate if Mobile Number is already in use
        const existingPhoneUser = await this.userRepository.findByPhoneNumber(data.phoneNumber);
        if (existingPhoneUser) {
            throw new Error('Mobile number is already registered');
        }

        // 3. Hash the password
        let finalPassword = data.password;
        if (finalPassword) {
            finalPassword = await this.passwordService.hash(finalPassword);
        }

        // 4. Generate referralId
        const namePart = (data.username || 'USER').substring(0, 4).toUpperCase();
        const randPart = Math.floor(1000 + Math.random() * 9000).toString();
        const referralId = namePart + randPart;

        // 5. Check if referred by someone
        let referredByUserId: string | undefined = undefined;
        if (data.referralCode) {
            const referrer = await UserModel.findOne({ referralId: data.referralCode });
            if (referrer) {
                referredByUserId = referrer._id.toString();
            }
        }

        // 6. Create new user entity
        const newUser = new User(
            '', // id will be generated by the database
            data.email,
            data.username, // displayName
            data.username, // username
            data.phoneNumber,
            finalPassword,
            UserRole.USER,
            false, // verified is false initially
            undefined, // imageUrl
            referralId,
            referredByUserId,
            [], // addresses
            new Date(),
            new Date()
        );

        // 7. Save the user
        const savedUser = await this.userRepository.save(newUser);

        // 7. Create Wallet for User
        await WalletModel.create({ userId: savedUser.id });

        // 8. Generate Verification OTP and save it
        const otpToken = crypto.randomBytes(32).toString('hex');

        await UserOTPVerificationModel.create({
            email: savedUser.email,
            otp: otpToken
        });

        // 9. Send the verification Email
        await this.emailService.sendVerificationEmail(savedUser.email, otpToken);

        // 7. Return response (No JWT tokens since verified: false)
        const { password: _, ...userWithoutPassword } = savedUser;

        return {
            user: userWithoutPassword as any,
            message: 'Registration successful. Please verify your email to continue.'
        };
    }
}
